apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sentiment-app
  labels:
    app: flask-sentiment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-sentiment-app
  template:
    metadata:
      labels:
        app: flask-sentiment-app
    spec:
      containers:
      - name: flask-sentiment-app
        image: evansabraham/flask-sentiment-app
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-sentiment-app
spec:
  selector:
    app: flask-sentiment-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
