apiVersion: v1
kind: Service
metadata:
  name: flask-sentiment-app
spec:
  selector:
    app: flask-sentiment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
